/* ============================================================
   Oracle ERP Core Schema
   ============================================================ */

-- ========================
-- Employees
-- ========================
CREATE TABLE employees (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_number VARCHAR2(50) UNIQUE NOT NULL,
    full_name       VARCHAR2(255) NOT NULL,
    department      VARCHAR2(100),
    status          VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT chk_employee_status
        CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

-- ========================
-- Assets
-- ========================
CREATE TABLE assets (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_tag       VARCHAR2(100) UNIQUE NOT NULL,
    asset_name      VARCHAR2(255) NOT NULL,
    asset_type      VARCHAR2(100),
    purchase_date   DATE,
    cost            NUMBER(12,2),
    status          VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT chk_asset_status
        CHECK (status IN ('ACTIVE', 'RETIRED'))
);

-- ========================
-- Asset Assignments
-- ========================
CREATE TABLE asset_assignments (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id        NUMBER NOT NULL,
    employee_id     NUMBER NOT NULL,
    assigned_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    return_date     TIMESTAMP,
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT fk_assignment_asset
        FOREIGN KEY (asset_id)
        REFERENCES assets(id),

    CONSTRAINT fk_assignment_employee
        FOREIGN KEY (employee_id)
        REFERENCES employees(id)
);

-- ========================
-- Timesheets
-- ========================
CREATE TABLE timesheets (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id     NUMBER NOT NULL,
    work_date       DATE NOT NULL,
    hours           NUMBER(5,2) NOT NULL,
    status          VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL,
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT fk_timesheet_employee
        FOREIGN KEY (employee_id)
        REFERENCES employees(id),

    CONSTRAINT chk_timesheet_hours
        CHECK (hours >= 0 AND hours <= 24),

    CONSTRAINT uq_timesheet_per_day
        UNIQUE (employee_id, work_date)
);

-- ========================
-- Approvals
-- ========================
CREATE TABLE approvals (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference_type  VARCHAR2(50) NOT NULL,
    reference_id    NUMBER NOT NULL,
    approved_by     NUMBER NOT NULL,
    approval_status VARCHAR2(20) NOT NULL,
    approved_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    comments        VARCHAR2(500),

    CONSTRAINT fk_approval_approver
        FOREIGN KEY (approved_by)
        REFERENCES employees(id),

    CONSTRAINT chk_approval_status
        CHECK (approval_status IN ('APPROVED', 'REJECTED'))
);

-- ========================
-- Indexing Strategy
-- ========================
CREATE INDEX idx_assets_status
    ON assets(status);

CREATE INDEX idx_asset_assignments_active
    ON asset_assignments(asset_id, return_date);

CREATE INDEX idx_timesheets_employee_date
    ON timesheets(employee_id, work_date);

CREATE INDEX idx_timesheets_status
    ON timesheets(status);

CREATE INDEX idx_approvals_reference
    ON approvals(reference_type, reference_id);

CREATE INDEX idx_approvals_status
    ON approvals(approval_status);

